SELECT * FROM ANIMAL_INS ORDER BY ANIMAL_ID;

SELECT NAME, DATETIME FROM ANIMAL_INS ORDER BY ANIMAL_ID DESC;

SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION='Sick' ORDER BY ANIMAL_ID;

SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION != 'Aged';

SELECT ANIMAL_ID, NAME FROM ANIMAL_INS ORDER BY ANIMAL_ID;

SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS ORDER BY NAME, DATETIME DESC;

SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME LIMIT 1;

SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME DESC LIMIT 1;

SELECT DATETIME AS 시간 FROM ANIMAL_INS ORDER BY DATETIME LIMIT 1;

SELECT COUNT(ANIMAL_ID) FROM ANIMAL_INS

SELECT COUNT(DISTINCT NAME) FROM ANIMAL_INS WHERE NAME IS NOT NULL;

SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS "count" FROM ANIMAL_INS GROUP BY ANIMAL_TYPE ORDER BY ANIMAL_TYPE;

SELECT NAME, COUNT(NAME) as "COUNT" FROM ANIMAL_INS WHERE NAME IS NOT NULL GROUP BY NAME HAVING COUNT(NAME) > 1 ORDER BY NAME;

SELECT hour(DATETIME) as hour, count(datetime) as count FROM ANIMAL_OUTS WHERE hour(DATETIME) between 9 and 19 GROUP BY hour ORDER BY hour;






